#
# Target: MySQL 
# Syntax: mysql -u user password < filename.sql
# 
# Date  : Dec 07 2018 16:28
# Script Generated by Database Design Studio 2.21.3 
#


#
# Select Database: 'db_name'
#
USE db_name;

#
# Create Table    : 'utente'   
# id_utente       :  
# nomeutente      :  
# cognomeutente   :  
# indirizzo       :  
# citta           :  
# cap             :  
# nazione         :  
# data_nascita    :  
# mail            :  
# password        :  
#
CREATE TABLE utente (
    id_utente      INT NOT NULL AUTO_INCREMENT UNIQUE,
    nomeutente     CHAR(50) NOT NULL,
    cognomeutente  CHAR(50) NOT NULL,
    indirizzo      CHAR(50) NOT NULL,
    citta          CHAR(50) NOT NULL,
    cap            INT NOT NULL,
    nazione        CHAR(50) NOT NULL,
    data_nascita   DATE NOT NULL,
    mail           CHAR(50) NOT NULL,
    password       CHAR(50) NOT NULL,
PRIMARY KEY (id_utente)) TYPE=INNODB;

#
# Create Table    : 'cantina'   
# nomecantina     :  
# descrizionecantina :  
# num_telefono    :  
# num_fax         :  
#
CREATE TABLE cantina (
    nomecantina    CHAR(50) NOT NULL UNIQUE,
    descrizionecantina CHAR(50) NOT NULL,
    num_telefono   CHAR(50) NOT NULL,
    num_fax        CHAR(50) NOT NULL,
PRIMARY KEY (nomecantina)) TYPE=INNODB;

#
# Create Table    : 'stock'   
# prezzostock     :  
# qta_stock       :  
# data_aggiunta   :  
# status          :  
# codice_stock    :  
#
CREATE TABLE stock (
    prezzostock    FLOAT(50) NOT NULL,
    qta_stock      INT NOT NULL,
    data_aggiunta  DATETIME NOT NULL,
    status         CHAR(10) NOT NULL,
    codice_stock   INT NOT NULL AUTO_INCREMENT UNIQUE,
PRIMARY KEY (codice_stock)) TYPE=INNODB;

#
# Create Table    : 'tipo'   
# id_tipo         :  
# descrizionetipo :  
#
CREATE TABLE tipo (
    id_tipo        CHAR(50) NOT NULL UNIQUE,
    descrizionetipo CHAR(200) NOT NULL,
PRIMARY KEY (id_tipo)) TYPE=INNODB;

#
# Create Table    : 'prodotto'   
# id_prodotto     :  
# nomeprodotto    :  
# annoprodotto    :  
# descrizioneprodotto :  
# nomecantina     :  (references cantina.nomecantina)
# categoriaprodotto :  
# codice_stock    :  (references stock.codice_stock)
# categoria       :  (references tipo.id_tipo)
#
CREATE TABLE prodotto (
    id_prodotto    INT NOT NULL AUTO_INCREMENT UNIQUE,
    nomeprodotto   CHAR(50) NOT NULL,
    annoprodotto   INT NOT NULL,
    descrizioneprodotto CHAR(1000) NOT NULL,
    nomecantina    CHAR(50) NOT NULL,
    categoriaprodotto CHAR(1000) NOT NULL,
    codice_stock   INT NOT NULL,
    categoria      CHAR(50) NOT NULL,
PRIMARY KEY (id_prodotto),
    INDEX idx_fk_prodotto (nomecantina),
CONSTRAINT fk_prodotto FOREIGN KEY (nomecantina)
    REFERENCES cantina (nomecantina)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    INDEX idx_fk_prodotto2 (codice_stock),
CONSTRAINT fk_prodotto2 FOREIGN KEY (codice_stock)
    REFERENCES stock (codice_stock)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    INDEX idx_fk_prodotto3 (categoria),
CONSTRAINT fk_prodotto3 FOREIGN KEY (categoria)
    REFERENCES tipo (id_tipo)
    ON DELETE RESTRICT
    ON UPDATE CASCADE) TYPE=INNODB;

#
# Create Table    : 'ordine'   
# id_ordine       :  
# qta_ordine      :  
# id_utente       :  (references utente.id_utente)
# id_prodotto     :  (references prodotto.id_prodotto)
#
CREATE TABLE ordine (
    id_ordine      INT NOT NULL AUTO_INCREMENT UNIQUE,
    qta_ordine     INT NOT NULL,
    id_utente      INT NOT NULL,
    id_prodotto    INT NOT NULL,
PRIMARY KEY (id_ordine),
    INDEX idx_fk_ordine (id_utente),
CONSTRAINT fk_ordine FOREIGN KEY (id_utente)
    REFERENCES utente (id_utente)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    INDEX idx_fk_ordine2 (id_prodotto),
CONSTRAINT fk_ordine2 FOREIGN KEY (id_prodotto)
    REFERENCES prodotto (id_prodotto)
    ON DELETE RESTRICT
    ON UPDATE CASCADE) TYPE=INNODB;

#
# Create Table    : 'dettagli'   
# id_dettagli     :  
# id_ordine       :  (references ordine.id_ordine)
# id_prodotto     :  (references prodotto.id_prodotto)
#
CREATE TABLE dettagli (
    id_dettagli    INT NOT NULL UNIQUE,
    id_ordine      INT NOT NULL,
    id_prodotto    INT NOT NULL,
PRIMARY KEY (id_dettagli),
    INDEX idx_fk_dettagli (id_ordine),
CONSTRAINT fk_dettagli FOREIGN KEY (id_ordine)
    REFERENCES ordine (id_ordine)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    INDEX idx_fk_dettagli2 (id_prodotto),
CONSTRAINT fk_dettagli2 FOREIGN KEY (id_prodotto)
    REFERENCES prodotto (id_prodotto)
    ON DELETE RESTRICT
    ON UPDATE CASCADE) TYPE=INNODB;

